package com.techelevator.ui.asciiArt;

public class Umbrella {
//    public static void printUmbrella(){
//
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("##################################################@################################################@@#################################################");
//        System.out.println("###############################################W##xxM@##########################################@Mxx@#W###############################################");
//        System.out.println("##############################################M:##MnnnxMW@##################################@WMxnnnM##;M##############################################");
//        System.out.println("##############################################i M#@xnnnnnxxMW@@########################@@WMxxnnnnnn@#M i##############################################");
//        System.out.println("#############################################M` i##MnnnnnnnnnnxxMMWW@@@########@@@WWMMxxnnnnnnnnxnx##* `M#############################################");
//        System.out.println("############################################@i  `@#@nnnnnnnnnnnnnnnnnnxxxxxxxxxxnnnnnnnnnnnnnnnnnnW#@`  i@############################################");
//        System.out.println("############################################x    ###xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##z    x############################################");
//        System.out.println("###########################################@:    ,##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##,    :@###########################################");
//        System.out.println("###########################################z      x#@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#x      z###########################################");
//        System.out.println("##########################################W.      ;##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##i      .W##########################################");
//        System.out.println("#########################################@*       `W#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@#W`       i@#########################################");
//        System.out.println("#########################################x`        +##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###        `n#########################################");
//        System.out.println("########################################W,         .##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##.         ,W########################################");
//        System.out.println("#######################################@i           n#@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#n           i@#######################################");
//        System.out.println("#######################################z            :##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##;            z#######################################");
//        System.out.println("######################################M.             M#@xxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@#W             `M######################################");
//        System.out.println("#####################################W,              *##Mnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##*              ,W#####################################");
//        System.out.println("####################################@i               `@#WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW#@.               ;@####################################");
//        System.out.println("###################################@+                 z##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#z                 *@###################################");
//        System.out.println("##################################@#                  ,##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##:                  #@##################################");
//        System.out.println("#################################@n`                   x#@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@#M                   `z@#################################");
//        System.out.println("################################@n`                    i##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##i                    `z@################################");
//        System.out.println("###############################@n`                     `W#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW#@`                     `z@###############################");
//        System.out.println("###############################n`                       +##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###                       `z@##############################");
//        System.out.println("#############################@n`                        .@#WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##,                        `z@#############################");
//        System.out.println("############################@z`                          n##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#x                          `#@############################");
//        System.out.println("###########################@+                            ;##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##;                            *@###########################");
//        System.out.println("##########################Wi                              W#@nnnnnnnnnnnnnnnnnnnnnnnnnnnn@#W`                             ;W##########################");
//        System.out.println("#########################M,                               *##Mnxnnnnnnnnnnnnnnnnnnnnnnnnx##+                               ,M#########################");
//        System.out.println("#######################@z.                                .@#WnxnnnnnnnnnnnnnnnnnnnnnnnnW#@.                                `z@#######################");
//        System.out.println("######################W*                                   z##xnnnnnnnnnnnnnnnnnnnnnnnnx@#n                                   iW######################");
//        System.out.println("####################@x,                                    :##WnxnnnnnnnnnnnnnnnnnnnnnnM##:                                    ,n@####################");
//        System.out.println("###################W*`                                      M#@xnnnnnnnnnnnnnnnnnnnnnnn@#M                                      `iW###################");
//        System.out.println("#################@z.                                        i##Mnnnnnnnnnnnnnnnnnnnnnnx##*                                        .z@#################");
//        System.out.println("###############@x:                                          `@#@nnnnnnnnnnnnnnnnnnnnnnW#@`                                          :x@###############");
//        System.out.println("##############Mi`                                            ###xnnnnnnnnnnnnnnnnnnnnx###                                            `iM##############");
//        System.out.println("############Wi`                                              ,##WnnnnnnnnnnnnnnnnnnnnW##,                                              `iM############");
//        System.out.println("###########M,                                                 n#@xnnnnnnnnnnnnnnnnnnn@#x                                                 .M###########");
//        System.out.println("############@n;                                               ;##MnnnnnnnnnnnnnnnnnnM##i                                               :z@############");
//        System.out.println("###############W*`                                            `W#@nnnnnnnnnnnnnnnnnn@#W`                                            `*M###############");
//        System.out.println("##########@xW####@z:                                           +##xnnnnnnnnnnnnnnnnx##+                                           ,#@####Wx@##########");
//        System.out.println("###########xnxW@####Mi`                                        .@#WnnnnnnnnnnnnnnnnW#@.                                        `ix####@Mxnx###########");
//        System.out.println("###########MnnnnM@####@#,                                       z#@xnnnnnnnnnnnnnnx@#n                                       .+W####WMnnnnM###########");
//        System.out.println("###########@nnnnnnxW@####x;                                     :##MnnnnnnnnnnnnnnM##;                                     :n@###@Wxnnnnnn@###########");
//        System.out.println("############xnnnnnnnxM@####W+.                                   M#@xnnnnnnnnnnnnn@#M`                                  `*M####@Mxnnnnnnnx############");
//        System.out.println("############MnnnnnnnnnnxW@###@z:                                 *##Mnnnnnnnnnnnnx##*                                 :z@###@WxnnnnnnnnnnM############");
//        System.out.println("############WnnnnnnnnnnnnxM@####Mi`                              `@#WnnnnnnnnnnnnW#@.                              `ix####@MxnnnnnnnnnnnnW############");
//        System.out.println("############@xnnnnnnnnnnnnnxMW####@#,                             ###xnnnnnnnnnnx@#z                             ,#@####WMnnxnnnnnnnnnnnx@############");
//        System.out.println("#############xnnnnnnnnnnnnnnnnxW@####xi`                          ,##WnnnnnnnnxnM##:                          `;n@###@Wxnnnnnnnnnnnnnnnnx#############");
//        System.out.println("#############MnnnnnnnnnnnnnnnnnnxM@####W+.                         x#@xnnnnnnnnx@#x                         .+W####@MxnnnnnnnnnnnnnnnnnnM#############");
//        System.out.println("#############WnnnnnnnnnnnnnnnnnnnnnxW@####n:                       i##MnnnnnnnnM##i                       :z@###@WxnnnnnnnnnnnnnnnnnnnnnW#############");
//        System.out.println("#############@nnnnnnnnnnnnnnnnnnnnnnnxM@####M*`                    `W#@nnnnnnnnW#@`                    `iM####@Mxnnnnnnnnnnnnnnnnnnnnnnn@#############");
//        System.out.println("#############@xnnnnnnnnnnnnnnnnnnnnnnnnnMW####@z,                   +##xnnnnnnx###                   ,#@####Wxnnxnnnnnnnnnnnnnnnnnnnnnnx@#############");
//        System.out.println("##############xnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####xi`                .@#WnnnnnnW##,                `;x####@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnx##############");
//        System.out.println("##############MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####W#,               n#@xnnnnx@#n               .+W####@MxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##############");
//        System.out.println("##############MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW@###@n;             :##MnnnnM##;             :n@###@WxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##############");
//        System.out.println("##############WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####W+.           M#@nnnn@#W           `*M####@MxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##############");
//        System.out.println("##############WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW####@z:         *##Mnnx##+         ,z@####WxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##############");
//        System.out.println("##############@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####Mi`      `@#WnnW#@.      `ix####@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@##############");
//        System.out.println("##############@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxMW####@#,     z##xx@#z     .#W####WMnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@##############");
//        System.out.println("##############@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxxW@####x;`  ,##WM##:  `;n@###@Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@##############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####W+. x#@@#M .*W####@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW####@nz####zz@####Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@############@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnMW#######@Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@######@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW@###########Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####Wn####xW####@Mxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("###############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW@####x;`n##@#x`;x@###@Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###############");
//        System.out.println("##############@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW####@#,  .##WW##,  ,#@####WMxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@##############");
//        System.out.println("##############@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####Mi`    +##xx###    `iM####@Mxnnxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@##############");
//        System.out.println("##############@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW@###@z:      `W#@nnW#@`      :z@####Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@##############");
//        System.out.println("##############WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####W*.        i##MnnM##i        .*M####@MxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##############");
//        System.out.println("##############WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW@###@n;           x#@xnnn@#M           ;n@###@WxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##############");
//        System.out.println("##############MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnMW####W#.            ,##WnnnnM##:            .+W####@MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##############");
//        System.out.println("##############MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxM@####xi`              z##xnnnnx@#z              `ix####@MxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##############");
//        System.out.println("##############xnnnnnnnnnnnnnnnnnnnnnnnnnnnnxW####@z,                `@#WnnnnnnW#@.                ,z@####Wxnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##############");
//        System.out.println("#############@xnnnnnnnnnnnnnnnnnnnnnnnnnxM@####M*`                  *##Mnnnnnnx##+                  `*M####@Mxnnnnnnnnnnnnnnnnnnnnnnnnnx@#############");
//        System.out.println("#############@nnnnnnnnnnnnnnnnnnnnnnnnxW@###@n:                     M#@nnnnnnnn@#W`                    :n@###@Wxnnnnnnnnnnnnnnnnnnnnnnnn@#############");
//        System.out.println("#############WnnnnnnnnnnnnnnnnnnnnnxM@####W+.                      :##MnnnnnnnnM##;                      .+W####@MxnnnnnnnnnnnnnnnnnnnnnW#############");
//        System.out.println("#############MnnnnnnnnnnnnnnnnnnnxW@####x;`                        n##xnnnnnnnnx@#n                        `;x@###@WxnnnnnnnnnnnnnnnnnnnM#############");
//        System.out.println("#############xnnnnnnnnnnnnnxnnnMW####@#,                          .@#WnnnnnnnnnnW#@.                          ,#W####WMxnnnnxnnnnnnnnnnnx#############");
//        System.out.println("############@xnnnnnnnnnnnxnnxM@####Mi`                            +##xnnnnnnnnnnx###                            `iM####@Mxnnnnnnnnnnnnnnx@############");
//        System.out.println("############WnnnnnnnnnnnnnxW@###@z:                              `W#@nnnnnnnnnnnnW#W`                              :z@###@WxxnnnnnnnnnnnnW############");
//        System.out.println("############MnnnnnnnnnnxM@####W+.                                ;##MnnnnnnnnnnnnM##i                                .*W####@MxnnnnnnnnnnM############");
//        System.out.println("############xnnnnnnnnxW@####n;                                   x#@xnnnnnnnnnnnnn@#x                                   ;n####@Wxnnnnnnnnx############");
//        System.out.println("###########@nnnnnnxMW####@#.                                    ,##WnnnnnnnnnnnnnnM##,                                    .+@####@Mnnnnnxn@###########");
//        System.out.println("###########MnnnnxM@####xi`                                      ###xnnnnnnnnnnnnnnx##z                                      `iM####@MxnnnnW###########");
//        System.out.println("###########xnnxW@###@z,                                        `@#@nnnnnnnnnnnnnnnnW#@.                                        ,z@####Wxnnx###########");
//        System.out.println("##########@xM@####M*`                                          i##Mnnnnnnnnnnnnnnnnx##*                                          `*M####@Mx@##########");
//        System.out.println("##########@@####n:                                             M#@xnnnnnnnnnnnnnnnnn@#M                                             ;n@###@@##########");
//        System.out.println("#############W+.                                              :##WnnnnnnnnnnnnnnnnnnM##:                                              .+W#############");
//        System.out.println("###########@*`                                                z##xnnnnnnnnnnnnnnnnnnx@#n                                                `i@###########");
//        System.out.println("############W+`                                              .@#WnxnnnnnnnnnnnnnnnnnnW#@.                                              `+W############");
//        System.out.println("##############W*`                                            +##Mnnnnnnnnnnnnnnnnnnnnx##+                                            `*W##############");
//        System.out.println("################Wi                                          `W#@xnnnnnnnnnnnnnnnnnnnnn@#W`                                          iM################");
//        System.out.println("#################@x,                                        ;##MnnnnnnnnnnnnnnnnnnnnnnM##i                                        ,x@#################");
//        System.out.println("###################@#`                                      n#@xnnnnnnnnnnnnnnnnnnnnnnx@#x                                      `+@###################");
//        System.out.println("#####################M:                                    ,##WnnnnnnnnnnnnnnnnnnnnnnnnW##,                                    :x#####################");
//        System.out.println("######################@+`                                  ###xnnnnnnnnnnnnnnnnnnnnnnnnx###                                  `+@######################");
//        System.out.println("#######################@x.                                `W#@nnnnnnnnnnnnnnnnnnnnnnnnnnW#@`                                .x########################");
//        System.out.println("#########################W:                               i##MnnnnnnnnnnnnnnnnnnnnnnnnnnM##*                               :W#########################");
//        System.out.println("##########################@*                              x#@xxnnnnnnnnnnnnnnnnnnnnnnnnnn@#M                              *@##########################");
//        System.out.println("###########################@#`                           ,##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##:                           `#@###########################");
//        System.out.println("############################@z`                          z##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#z                          `n@############################");
//        System.out.println("##############################n`                        `@#WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW#@.                        `n@#############################");
//        System.out.println("###############################x.                       *##Mnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##+                       `n###############################");
//        System.out.println("################################x.                      M#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@#W`                     `n################################");
//        System.out.println("#################################x.                    :##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##;                    `n#################################");
//        System.out.println("##################################x`                   n##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#x                   `n##################################");
//        System.out.println("##################################@z`                 .@#WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##,                 `z###################################");
//        System.out.println("###################################@#                 +##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx###                 +@###################################");
//        System.out.println("####################################@*               `W#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW#@`               i@####################################");
//        System.out.println("#####################################@:              ;##MnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##i              :@#####################################");
//        System.out.println("######################################W.             x#@xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#x             .M######################################");
//        System.out.println("#######################################n`           ,##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##:            n#######################################");
//        System.out.println("#######################################@+           ###xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##z           *@#######################################");
//        System.out.println("########################################@:         `@#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW#@`         ,@########################################");
//        System.out.println("#########################################x`        *##Mnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##*        `x#########################################");
//        System.out.println("##########################################+        M#@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn@#W        *@#########################################");
//        System.out.println("##########################################@,      :##WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnM##;      .W##########################################");
//        System.out.println("###########################################x      z##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx@#n      n###########################################");
//        System.out.println("###########################################@i    .@#WnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnW##.    ;@###########################################");
//        System.out.println("############################################M`   +##xnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnx##+    x############################################");
//        System.out.println("#############################################*   W#@nnnnnnnnnnnnnnnnnnnxxxxxxxxxnnnnnnnnnnnnnnnnnn@#W`  i#############################################");
//        System.out.println("#############################################W` ;##MnnnnnnnnnnxxMMW@@@@########@@@WWMMxxnnnnnnnnnnM##i `M#############################################");
//        System.out.println("##############################################* n#@xnnnnnxxMW@##########################@WMxxnnnnnn@#x i##############################################");
//        System.out.println("##############################################W,##WnnnxMW@##################################@WMxnnnW##,M##############################################");
//        System.out.println("###############################################W##xxW@##########################################@Wxx@#W###############################################");
//        System.out.println("##################################################@################################################@##################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        System.out.println("######################################################################################################################################################");
//        }

//    public static void printUmbrella() {
//                System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@@@@@        (@@@@@@@@@@@@@/        @@@@@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@@@.  *  @@@@@@@@@@@@@@@@@@@@@@@  *  /@@@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@&  ****  @@@@@@@@@@@@@@@@@@@@@  ****  @@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@  ,******  @@@@@@@@@@@@@@@@@@@  ******,  @@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@.  **********  @@@@@@@@@@@@@@@@& .*********,  /@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@&   *************  @@@@@@@@@@@@@@% .*************   @@@@@@@@@");
//                System.out.println("@@@@@@   .*****************  @@@@@@@@@@@@( .*****************   .@@@@@");
//                System.out.println("%    .**********************. &@@@@@@@@@/ ,**********************"     );
//                System.out.println("@       *********************. #@@@@@@@, ,*********************    ."  );
//                System.out.println("@@  @@@@@     ****************. (@@@@@. ,****************    ,@@@@@  @");
//                System.out.println("@@( /@@@@@@@@@@.    ***********, /@@@  ************    *@@@@@@@@@@  &@");
//                System.out.println("@@@  @@@@@@@@@@@@@@@@.    ******, ,@  *******    /@@@@@@@@@@@@@@@@  @@");
//                System.out.println("@@@  @@@@@@@@@@@@@@@@@@@@@@,    *,   **    /@@@@@@@@@@@@@@@@@@@@@@  @@");
//                System.out.println("@@@  @@@@@@@@@@@@@@@@@@@@@@@@@@@@     @@@@@@@@@@@@@@@@@@@@@@@@@@@@ *@@");
//                System.out.println("@@@  @@@@@@@@@@@@@@@@@@@@@@     *,   **    .@@@@@@@@@@@@@@@@@@@@@@ ,@@");
//                System.out.println("@@@  @@@@@@@@@@@@@@@@     ******, /@  *******     @@@@@@@@@@@@@@@@  @@");
//                System.out.println("@@@ /@@@@@@@@@@    .***********, #@@@. ************     @@@@@@@@@@  @@");
//                System.out.println("@@  @@@@@    .****************. %@@@@@* ,****************     @@@@@  @");
//                System.out.println("@      .*********************. &@@@@@@@/ ,*********************.     .");
//                System.out.println("@@*   **********************  @@@@@@@@@@( ,**********************   #@");
//                System.out.println("@@@@@@@   *****************  @@@@@@@@@@@@% .*****************   @@@@@@");
//                System.out.println("@@@@@@@@@@   *************  @@@@@@@@@@@@@@& .*************   @@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@  **********  @@@@@@@@@@@@@@@@@  *********,  @@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@  ,******  @@@@@@@@@@@@@@@@@@@  ******.  @@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@@  ****  @@@@@@@@@@@@@@@@@@@@@  ****  @@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@@@*  *  @@@@@@@@@@@@@@@@@@@@@@@  *  %@@@@@@@@@@@@@@@@@");
//                System.out.println("@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@@@@@@        @@@@@@@@@@@@@@@@@@@");
//    }

    public static void printUmbrella() {
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@@@ , @@             @@ . @@@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@  **, @@@@@@@@@@@@@@@ ***  @@@@@@@@@@@");
        System.out.println("@@@@@@@@@@  ****** @@@@@@@@@@@@@ ******  @@@@@@@@@");
        System.out.println("@@@@@@@@  ********* @@@@@@@@@@@ *********  @@@@@@@");
        System.out.println("@@@@&  ************* @@@@@@@@@ *************  @@@@");
        System.out.println("@  ****************** @@@@@@@ ******************"  );
        System.out.println("@  @@@   ************* @@@@@ *************   @@@ %");
        System.out.println("@@ @@@@@@@@@   ******** @@@ *******,   @@@@@@@@. @");
        System.out.println("@@  @@@@@@@@@@@@@@   ,** @ **,   @@@@@@@@@@@@@@ ,@");
        System.out.println("@@% @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@ @@");
        System.out.println("@@. @@@@@@@@@@@@@@   *** @ ***   @@@@@@@@@@@@@@ @@");
        System.out.println("@@ @@@@@@@@&   ******** @@@ ********   @@@@@@@@, @");
        System.out.println("@% @@%   ************* @@@@@ *************   @@@ @");
        System.out.println("@  ****************** @@@@@@@ ******************"  );
        System.out.println("@@@@@  ************* @@@@@@@@@ *************  @@@@");
        System.out.println("@@@@@@@@  ********* @@@@@@@@@@@ *********  @@@@@@@");
        System.out.println("@@@@@@@@@@( ****** @@@@@@@@@@@@@ ****** @@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@  **, @@@@@@@@@@@@@@@ *** (@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@@@ . @,             /@   @@@@@@@@@@@@@");
    }

    public static void printUmbrellaWithColor() {
        System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%@@@@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@@@ , @@             @@ . @@@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@  **, @@@@@@@@@@@@@@@ ***  @@@@@@@@@@@");
        System.out.println("@@@@@@@@@@  ****** @@@@@@@@@@@@@ ******  @@@@@@@@@");
        System.out.println("@@@@@@@@  ********* @@@@@@@@@@@ *********  @@@@@@@");
        System.out.println("@@@@&  ************* @@@@@@@@@ *************  @@@@");
        System.out.println("@  ****************** @@@@@@@ ******************"  );
        System.out.println("@  @@@   ************* @@@@@ *************   @@@ %");
        System.out.println("@@ @@@@@@@@@   ******** @@@ *******,   @@@@@@@@. @");
        System.out.println("@@  @@@@@@@@@@@@@@   ,** @ **,   @@@@@@@@@@@@@@ ,@");
        System.out.println("@@% @@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@@@@@@@@@@ @@");
        System.out.println("@@. @@@@@@@@@@@@@@   *** @ ***   @@@@@@@@@@@@@@ @@");
        System.out.println("@@ @@@@@@@@&   ******** @@@ ********   @@@@@@@@, @");
        System.out.println("@% @@%   ************* @@@@@ *************   @@@ @");
        System.out.println("@  ****************** @@@@@@@ ******************"  );
        System.out.println("@@@@@  ************* @@@@@@@@@ *************  @@@@");
        System.out.println("@@@@@@@@  ********* @@@@@@@@@@@ *********  @@@@@@@");
        System.out.println("@@@@@@@@@@( ****** @@@@@@@@@@@@@ ****** @@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@  **, @@@@@@@@@@@@@@@ *** (@@@@@@@@@@@");
        System.out.println("@@@@@@@@@@@@@@ . @,             /@   @@@@@@@@@@@@@");
    }
}
